#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="familydbFULL")]
	public partial class DatabaseFamilyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertarea(area instance);
    partial void Updatearea(area instance);
    partial void Deletearea(area instance);
    partial void Insertchurch(church instance);
    partial void Updatechurch(church instance);
    partial void Deletechurch(church instance);
    partial void Insertfamily(family instance);
    partial void Updatefamily(family instance);
    partial void Deletefamily(family instance);
    partial void Inserthousetype(housetype instance);
    partial void Updatehousetype(housetype instance);
    partial void Deletehousetype(housetype instance);
    partial void Insertkhedma(khedma instance);
    partial void Updatekhedma(khedma instance);
    partial void Deletekhedma(khedma instance);
    partial void Insertmamodia(mamodia instance);
    partial void Updatemamodia(mamodia instance);
    partial void Deletemamodia(mamodia instance);
    partial void Insertmaritalstatus(maritalstatus instance);
    partial void Updatemaritalstatus(maritalstatus instance);
    partial void Deletemaritalstatus(maritalstatus instance);
    partial void Insertpriest(priest instance);
    partial void Updatepriest(priest instance);
    partial void Deletepriest(priest instance);
    partial void Insertshmosia(shmosia instance);
    partial void Updateshmosia(shmosia instance);
    partial void Deleteshmosia(shmosia instance);
    partial void Insertresponsiblepriest(responsiblepriest instance);
    partial void Updateresponsiblepriest(responsiblepriest instance);
    partial void Deleteresponsiblepriest(responsiblepriest instance);
    partial void Insertstreet(street instance);
    partial void Updatestreet(street instance);
    partial void Deletestreet(street instance);
    partial void Insertvisitdetail(visitdetail instance);
    partial void Updatevisitdetail(visitdetail instance);
    partial void Deletevisitdetail(visitdetail instance);
    partial void Insertvisitkind(visitkind instance);
    partial void Updatevisitkind(visitkind instance);
    partial void Deletevisitkind(visitkind instance);
    #endregion
		
		public DatabaseFamilyDataContext() : 
				base(global::WPF.Properties.Settings.Default.familydbFULLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseFamilyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseFamilyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseFamilyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseFamilyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<area> areas
		{
			get
			{
				return this.GetTable<area>();
			}
		}
		
		public System.Data.Linq.Table<church> churches
		{
			get
			{
				return this.GetTable<church>();
			}
		}
		
		public System.Data.Linq.Table<calldetail> calldetails
		{
			get
			{
				return this.GetTable<calldetail>();
			}
		}
		
		public System.Data.Linq.Table<Conversion_Error> Conversion_Errors
		{
			get
			{
				return this.GetTable<Conversion_Error>();
			}
		}
		
		public System.Data.Linq.Table<family> families
		{
			get
			{
				return this.GetTable<family>();
			}
		}
		
		public System.Data.Linq.Table<familydetail> familydetails
		{
			get
			{
				return this.GetTable<familydetail>();
			}
		}
		
		public System.Data.Linq.Table<housetype> housetypes
		{
			get
			{
				return this.GetTable<housetype>();
			}
		}
		
		public System.Data.Linq.Table<khedma> khedmas
		{
			get
			{
				return this.GetTable<khedma>();
			}
		}
		
		public System.Data.Linq.Table<mamodia> mamodias
		{
			get
			{
				return this.GetTable<mamodia>();
			}
		}
		
		public System.Data.Linq.Table<maritalstatus> maritalstatus
		{
			get
			{
				return this.GetTable<maritalstatus>();
			}
		}
		
		public System.Data.Linq.Table<priest> priests
		{
			get
			{
				return this.GetTable<priest>();
			}
		}
		
		public System.Data.Linq.Table<reporttitle> reporttitles
		{
			get
			{
				return this.GetTable<reporttitle>();
			}
		}
		
		public System.Data.Linq.Table<shmosia> shmosias
		{
			get
			{
				return this.GetTable<shmosia>();
			}
		}
		
		public System.Data.Linq.Table<responsiblepriest> responsiblepriests
		{
			get
			{
				return this.GetTable<responsiblepriest>();
			}
		}
		
		public System.Data.Linq.Table<streetmap> streetmaps
		{
			get
			{
				return this.GetTable<streetmap>();
			}
		}
		
		public System.Data.Linq.Table<street> streets
		{
			get
			{
				return this.GetTable<street>();
			}
		}
		
		public System.Data.Linq.Table<visitdetail> visitdetails
		{
			get
			{
				return this.GetTable<visitdetail>();
			}
		}
		
		public System.Data.Linq.Table<visitkind> visitkinds
		{
			get
			{
				return this.GetTable<visitkind>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.areas")]
	public partial class area : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _areacode;
		
		private string _areaname;
		
		private EntitySet<family> _families;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnareacodeChanging(int value);
    partial void OnareacodeChanged();
    partial void OnareanameChanging(string value);
    partial void OnareanameChanged();
    #endregion
		
		public area()
		{
			this._families = new EntitySet<family>(new Action<family>(this.attach_families), new Action<family>(this.detach_families));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areacode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int areacode
		{
			get
			{
				return this._areacode;
			}
			set
			{
				if ((this._areacode != value))
				{
					this.OnareacodeChanging(value);
					this.SendPropertyChanging();
					this._areacode = value;
					this.SendPropertyChanged("areacode");
					this.OnareacodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areaname", DbType="NVarChar(100)")]
		public string areaname
		{
			get
			{
				return this._areaname;
			}
			set
			{
				if ((this._areaname != value))
				{
					this.OnareanameChanging(value);
					this.SendPropertyChanging();
					this._areaname = value;
					this.SendPropertyChanged("areaname");
					this.OnareanameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="area_family", Storage="_families", ThisKey="areacode", OtherKey="areacode")]
		public EntitySet<family> families
		{
			get
			{
				return this._families;
			}
			set
			{
				this._families.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.area = this;
		}
		
		private void detach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.area = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.churches")]
	public partial class church : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _churchcode;
		
		private string _churchname;
		
		private string _churchtel1;
		
		private string _churchtel2;
		
		private string _churchaddress;
		
		private EntitySet<family> _families;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnchurchcodeChanging(int value);
    partial void OnchurchcodeChanged();
    partial void OnchurchnameChanging(string value);
    partial void OnchurchnameChanged();
    partial void Onchurchtel1Changing(string value);
    partial void Onchurchtel1Changed();
    partial void Onchurchtel2Changing(string value);
    partial void Onchurchtel2Changed();
    partial void OnchurchaddressChanging(string value);
    partial void OnchurchaddressChanged();
    #endregion
		
		public church()
		{
			this._families = new EntitySet<family>(new Action<family>(this.attach_families), new Action<family>(this.detach_families));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchcode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int churchcode
		{
			get
			{
				return this._churchcode;
			}
			set
			{
				if ((this._churchcode != value))
				{
					this.OnchurchcodeChanging(value);
					this.SendPropertyChanging();
					this._churchcode = value;
					this.SendPropertyChanged("churchcode");
					this.OnchurchcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchname", DbType="NVarChar(100)")]
		public string churchname
		{
			get
			{
				return this._churchname;
			}
			set
			{
				if ((this._churchname != value))
				{
					this.OnchurchnameChanging(value);
					this.SendPropertyChanging();
					this._churchname = value;
					this.SendPropertyChanged("churchname");
					this.OnchurchnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchtel1", DbType="NVarChar(10)")]
		public string churchtel1
		{
			get
			{
				return this._churchtel1;
			}
			set
			{
				if ((this._churchtel1 != value))
				{
					this.Onchurchtel1Changing(value);
					this.SendPropertyChanging();
					this._churchtel1 = value;
					this.SendPropertyChanged("churchtel1");
					this.Onchurchtel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchtel2", DbType="NVarChar(10)")]
		public string churchtel2
		{
			get
			{
				return this._churchtel2;
			}
			set
			{
				if ((this._churchtel2 != value))
				{
					this.Onchurchtel2Changing(value);
					this.SendPropertyChanging();
					this._churchtel2 = value;
					this.SendPropertyChanged("churchtel2");
					this.Onchurchtel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchaddress", DbType="NVarChar(100)")]
		public string churchaddress
		{
			get
			{
				return this._churchaddress;
			}
			set
			{
				if ((this._churchaddress != value))
				{
					this.OnchurchaddressChanging(value);
					this.SendPropertyChanging();
					this._churchaddress = value;
					this.SendPropertyChanged("churchaddress");
					this.OnchurchaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="church_family", Storage="_families", ThisKey="churchcode", OtherKey="churchcode")]
		public EntitySet<family> families
		{
			get
			{
				return this._families;
			}
			set
			{
				this._families.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.church = this;
		}
		
		private void detach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.church = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.calldetails")]
	public partial class calldetail
	{
		
		private System.Nullable<int> _familycode;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _details;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		public calldetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familycode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> familycode
		{
			get
			{
				return this._familycode;
			}
			set
			{
				if ((this._familycode != value))
				{
					this._familycode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime2", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this._details = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this._SSMA_TimeStamp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Conversion Errors]")]
	public partial class Conversion_Error
	{
		
		private string _Object_Type;
		
		private string _Object_Name;
		
		private string _Error_Description;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		public Conversion_Error()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Object Type]", Storage="_Object_Type", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Object_Type
		{
			get
			{
				return this._Object_Type;
			}
			set
			{
				if ((this._Object_Type != value))
				{
					this._Object_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Object Name]", Storage="_Object_Name", DbType="NVarChar(255)", UpdateCheck=UpdateCheck.Never)]
		public string Object_Name
		{
			get
			{
				return this._Object_Name;
			}
			set
			{
				if ((this._Object_Name != value))
				{
					this._Object_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Error Description]", Storage="_Error_Description", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Error_Description
		{
			get
			{
				return this._Error_Description;
			}
			set
			{
				if ((this._Error_Description != value))
				{
					this._Error_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this._SSMA_TimeStamp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.family")]
	public partial class family : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _familycode;
		
		private string _familyname;
		
		private string _buildingnumber;
		
		private System.Nullable<short> _apparmentnumber;
		
		private System.Nullable<short> _floornumber;
		
		private System.Nullable<int> _streetcode;
		
		private string _familyaddress;
		
		private string _familytel;
		
		private System.Nullable<short> _familynumber;
		
		private System.Nullable<short> _economicstatus;
		
		private System.Nullable<int> _housetypecode;
		
		private System.Nullable<short> _home;
		
		private System.Nullable<int> _responsiblepriestcode;
		
		private System.Nullable<int> _churchcode;
		
		private System.Nullable<int> _areacode;
		
		private System.Nullable<System.DateTime> _lastvisitdate;
		
		private string _priestname;
		
		private System.Nullable<bool> _computerfl;
		
		private System.Nullable<bool> _dishfl;
		
		private string _familytel2;
		
		private System.Nullable<System.DateTime> _marriagedate;
		
		private System.Nullable<bool> _marriagedatefl;
		
		private string _comments;
		
		private System.Nullable<System.DateTime> _lastcalldate;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		private EntityRef<visitdetail> _visitdetail;
		
		private EntityRef<area> _area;
		
		private EntityRef<church> _church;
		
		private EntityRef<housetype> _housetype;
		
		private EntityRef<responsiblepriest> _responsiblepriest;
		
		private EntityRef<street> _street;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfamilycodeChanging(int value);
    partial void OnfamilycodeChanged();
    partial void OnfamilynameChanging(string value);
    partial void OnfamilynameChanged();
    partial void OnbuildingnumberChanging(string value);
    partial void OnbuildingnumberChanged();
    partial void OnapparmentnumberChanging(System.Nullable<short> value);
    partial void OnapparmentnumberChanged();
    partial void OnfloornumberChanging(System.Nullable<short> value);
    partial void OnfloornumberChanged();
    partial void OnstreetcodeChanging(System.Nullable<int> value);
    partial void OnstreetcodeChanged();
    partial void OnfamilyaddressChanging(string value);
    partial void OnfamilyaddressChanged();
    partial void OnfamilytelChanging(string value);
    partial void OnfamilytelChanged();
    partial void OnfamilynumberChanging(System.Nullable<short> value);
    partial void OnfamilynumberChanged();
    partial void OneconomicstatusChanging(System.Nullable<short> value);
    partial void OneconomicstatusChanged();
    partial void OnhousetypecodeChanging(System.Nullable<int> value);
    partial void OnhousetypecodeChanged();
    partial void OnhomeChanging(System.Nullable<short> value);
    partial void OnhomeChanged();
    partial void OnresponsiblepriestcodeChanging(System.Nullable<int> value);
    partial void OnresponsiblepriestcodeChanged();
    partial void OnchurchcodeChanging(System.Nullable<int> value);
    partial void OnchurchcodeChanged();
    partial void OnareacodeChanging(System.Nullable<int> value);
    partial void OnareacodeChanged();
    partial void OnlastvisitdateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastvisitdateChanged();
    partial void OnpriestnameChanging(string value);
    partial void OnpriestnameChanged();
    partial void OncomputerflChanging(System.Nullable<bool> value);
    partial void OncomputerflChanged();
    partial void OndishflChanging(System.Nullable<bool> value);
    partial void OndishflChanged();
    partial void Onfamilytel2Changing(string value);
    partial void Onfamilytel2Changed();
    partial void OnmarriagedateChanging(System.Nullable<System.DateTime> value);
    partial void OnmarriagedateChanged();
    partial void OnmarriagedateflChanging(System.Nullable<bool> value);
    partial void OnmarriagedateflChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnlastcalldateChanging(System.Nullable<System.DateTime> value);
    partial void OnlastcalldateChanged();
    partial void OnSSMA_TimeStampChanging(System.Data.Linq.Binary value);
    partial void OnSSMA_TimeStampChanged();
    #endregion
		
		public family()
		{
			this._visitdetail = default(EntityRef<visitdetail>);
			this._area = default(EntityRef<area>);
			this._church = default(EntityRef<church>);
			this._housetype = default(EntityRef<housetype>);
			this._responsiblepriest = default(EntityRef<responsiblepriest>);
			this._street = default(EntityRef<street>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familycode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int familycode
		{
			get
			{
				return this._familycode;
			}
			set
			{
				if ((this._familycode != value))
				{
					this.OnfamilycodeChanging(value);
					this.SendPropertyChanging();
					this._familycode = value;
					this.SendPropertyChanged("familycode");
					this.OnfamilycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familyname", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string familyname
		{
			get
			{
				return this._familyname;
			}
			set
			{
				if ((this._familyname != value))
				{
					this.OnfamilynameChanging(value);
					this.SendPropertyChanging();
					this._familyname = value;
					this.SendPropertyChanged("familyname");
					this.OnfamilynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buildingnumber", DbType="NVarChar(6)", UpdateCheck=UpdateCheck.Never)]
		public string buildingnumber
		{
			get
			{
				return this._buildingnumber;
			}
			set
			{
				if ((this._buildingnumber != value))
				{
					this.OnbuildingnumberChanging(value);
					this.SendPropertyChanging();
					this._buildingnumber = value;
					this.SendPropertyChanged("buildingnumber");
					this.OnbuildingnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apparmentnumber", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> apparmentnumber
		{
			get
			{
				return this._apparmentnumber;
			}
			set
			{
				if ((this._apparmentnumber != value))
				{
					this.OnapparmentnumberChanging(value);
					this.SendPropertyChanging();
					this._apparmentnumber = value;
					this.SendPropertyChanged("apparmentnumber");
					this.OnapparmentnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_floornumber", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> floornumber
		{
			get
			{
				return this._floornumber;
			}
			set
			{
				if ((this._floornumber != value))
				{
					this.OnfloornumberChanging(value);
					this.SendPropertyChanging();
					this._floornumber = value;
					this.SendPropertyChanged("floornumber");
					this.OnfloornumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_streetcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> streetcode
		{
			get
			{
				return this._streetcode;
			}
			set
			{
				if ((this._streetcode != value))
				{
					if (this._street.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstreetcodeChanging(value);
					this.SendPropertyChanging();
					this._streetcode = value;
					this.SendPropertyChanged("streetcode");
					this.OnstreetcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familyaddress", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string familyaddress
		{
			get
			{
				return this._familyaddress;
			}
			set
			{
				if ((this._familyaddress != value))
				{
					this.OnfamilyaddressChanging(value);
					this.SendPropertyChanging();
					this._familyaddress = value;
					this.SendPropertyChanged("familyaddress");
					this.OnfamilyaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familytel", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string familytel
		{
			get
			{
				return this._familytel;
			}
			set
			{
				if ((this._familytel != value))
				{
					this.OnfamilytelChanging(value);
					this.SendPropertyChanging();
					this._familytel = value;
					this.SendPropertyChanged("familytel");
					this.OnfamilytelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familynumber", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> familynumber
		{
			get
			{
				return this._familynumber;
			}
			set
			{
				if ((this._familynumber != value))
				{
					this.OnfamilynumberChanging(value);
					this.SendPropertyChanging();
					this._familynumber = value;
					this.SendPropertyChanged("familynumber");
					this.OnfamilynumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_economicstatus", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> economicstatus
		{
			get
			{
				return this._economicstatus;
			}
			set
			{
				if ((this._economicstatus != value))
				{
					this.OneconomicstatusChanging(value);
					this.SendPropertyChanging();
					this._economicstatus = value;
					this.SendPropertyChanged("economicstatus");
					this.OneconomicstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_housetypecode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> housetypecode
		{
			get
			{
				return this._housetypecode;
			}
			set
			{
				if ((this._housetypecode != value))
				{
					if (this._housetype.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhousetypecodeChanging(value);
					this.SendPropertyChanging();
					this._housetypecode = value;
					this.SendPropertyChanged("housetypecode");
					this.OnhousetypecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home", DbType="SmallInt", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<short> home
		{
			get
			{
				return this._home;
			}
			set
			{
				if ((this._home != value))
				{
					this.OnhomeChanging(value);
					this.SendPropertyChanging();
					this._home = value;
					this.SendPropertyChanged("home");
					this.OnhomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsiblepriestcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> responsiblepriestcode
		{
			get
			{
				return this._responsiblepriestcode;
			}
			set
			{
				if ((this._responsiblepriestcode != value))
				{
					if (this._responsiblepriest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnresponsiblepriestcodeChanging(value);
					this.SendPropertyChanging();
					this._responsiblepriestcode = value;
					this.SendPropertyChanged("responsiblepriestcode");
					this.OnresponsiblepriestcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> churchcode
		{
			get
			{
				return this._churchcode;
			}
			set
			{
				if ((this._churchcode != value))
				{
					if (this._church.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchurchcodeChanging(value);
					this.SendPropertyChanging();
					this._churchcode = value;
					this.SendPropertyChanged("churchcode");
					this.OnchurchcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areacode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> areacode
		{
			get
			{
				return this._areacode;
			}
			set
			{
				if ((this._areacode != value))
				{
					if (this._area.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnareacodeChanging(value);
					this.SendPropertyChanging();
					this._areacode = value;
					this.SendPropertyChanged("areacode");
					this.OnareacodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastvisitdate", DbType="DateTime2", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> lastvisitdate
		{
			get
			{
				return this._lastvisitdate;
			}
			set
			{
				if ((this._lastvisitdate != value))
				{
					this.OnlastvisitdateChanging(value);
					this.SendPropertyChanging();
					this._lastvisitdate = value;
					this.SendPropertyChanged("lastvisitdate");
					this.OnlastvisitdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priestname", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string priestname
		{
			get
			{
				return this._priestname;
			}
			set
			{
				if ((this._priestname != value))
				{
					this.OnpriestnameChanging(value);
					this.SendPropertyChanging();
					this._priestname = value;
					this.SendPropertyChanged("priestname");
					this.OnpriestnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_computerfl", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> computerfl
		{
			get
			{
				return this._computerfl;
			}
			set
			{
				if ((this._computerfl != value))
				{
					this.OncomputerflChanging(value);
					this.SendPropertyChanging();
					this._computerfl = value;
					this.SendPropertyChanged("computerfl");
					this.OncomputerflChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dishfl", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> dishfl
		{
			get
			{
				return this._dishfl;
			}
			set
			{
				if ((this._dishfl != value))
				{
					this.OndishflChanging(value);
					this.SendPropertyChanging();
					this._dishfl = value;
					this.SendPropertyChanged("dishfl");
					this.OndishflChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familytel2", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string familytel2
		{
			get
			{
				return this._familytel2;
			}
			set
			{
				if ((this._familytel2 != value))
				{
					this.Onfamilytel2Changing(value);
					this.SendPropertyChanging();
					this._familytel2 = value;
					this.SendPropertyChanged("familytel2");
					this.Onfamilytel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marriagedate", DbType="DateTime2", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> marriagedate
		{
			get
			{
				return this._marriagedate;
			}
			set
			{
				if ((this._marriagedate != value))
				{
					this.OnmarriagedateChanging(value);
					this.SendPropertyChanging();
					this._marriagedate = value;
					this.SendPropertyChanged("marriagedate");
					this.OnmarriagedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marriagedatefl", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> marriagedatefl
		{
			get
			{
				return this._marriagedatefl;
			}
			set
			{
				if ((this._marriagedatefl != value))
				{
					this.OnmarriagedateflChanging(value);
					this.SendPropertyChanging();
					this._marriagedatefl = value;
					this.SendPropertyChanged("marriagedatefl");
					this.OnmarriagedateflChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastcalldate", DbType="DateTime2", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> lastcalldate
		{
			get
			{
				return this._lastcalldate;
			}
			set
			{
				if ((this._lastcalldate != value))
				{
					this.OnlastcalldateChanging(value);
					this.SendPropertyChanging();
					this._lastcalldate = value;
					this.SendPropertyChanged("lastcalldate");
					this.OnlastcalldateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this.OnSSMA_TimeStampChanging(value);
					this.SendPropertyChanging();
					this._SSMA_TimeStamp = value;
					this.SendPropertyChanged("SSMA_TimeStamp");
					this.OnSSMA_TimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="family_visitdetail", Storage="_visitdetail", ThisKey="familycode", OtherKey="familycode", IsUnique=true, IsForeignKey=false)]
		public visitdetail visitdetail
		{
			get
			{
				return this._visitdetail.Entity;
			}
			set
			{
				visitdetail previousValue = this._visitdetail.Entity;
				if (((previousValue != value) 
							|| (this._visitdetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._visitdetail.Entity = null;
						previousValue.family = null;
					}
					this._visitdetail.Entity = value;
					if ((value != null))
					{
						value.family = this;
					}
					this.SendPropertyChanged("visitdetail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="area_family", Storage="_area", ThisKey="areacode", OtherKey="areacode", IsForeignKey=true)]
		public area area
		{
			get
			{
				return this._area.Entity;
			}
			set
			{
				area previousValue = this._area.Entity;
				if (((previousValue != value) 
							|| (this._area.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._area.Entity = null;
						previousValue.families.Remove(this);
					}
					this._area.Entity = value;
					if ((value != null))
					{
						value.families.Add(this);
						this._areacode = value.areacode;
					}
					else
					{
						this._areacode = default(Nullable<int>);
					}
					this.SendPropertyChanged("area");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="church_family", Storage="_church", ThisKey="churchcode", OtherKey="churchcode", IsForeignKey=true)]
		public church church
		{
			get
			{
				return this._church.Entity;
			}
			set
			{
				church previousValue = this._church.Entity;
				if (((previousValue != value) 
							|| (this._church.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._church.Entity = null;
						previousValue.families.Remove(this);
					}
					this._church.Entity = value;
					if ((value != null))
					{
						value.families.Add(this);
						this._churchcode = value.churchcode;
					}
					else
					{
						this._churchcode = default(Nullable<int>);
					}
					this.SendPropertyChanged("church");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="housetype_family", Storage="_housetype", ThisKey="housetypecode", OtherKey="housetypecode", IsForeignKey=true)]
		public housetype housetype
		{
			get
			{
				return this._housetype.Entity;
			}
			set
			{
				housetype previousValue = this._housetype.Entity;
				if (((previousValue != value) 
							|| (this._housetype.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._housetype.Entity = null;
						previousValue.families.Remove(this);
					}
					this._housetype.Entity = value;
					if ((value != null))
					{
						value.families.Add(this);
						this._housetypecode = value.housetypecode;
					}
					else
					{
						this._housetypecode = default(Nullable<int>);
					}
					this.SendPropertyChanged("housetype");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="responsiblepriest_family", Storage="_responsiblepriest", ThisKey="responsiblepriestcode", OtherKey="responsiblepriestcode", IsForeignKey=true)]
		public responsiblepriest responsiblepriest
		{
			get
			{
				return this._responsiblepriest.Entity;
			}
			set
			{
				responsiblepriest previousValue = this._responsiblepriest.Entity;
				if (((previousValue != value) 
							|| (this._responsiblepriest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._responsiblepriest.Entity = null;
						previousValue.families.Remove(this);
					}
					this._responsiblepriest.Entity = value;
					if ((value != null))
					{
						value.families.Add(this);
						this._responsiblepriestcode = value.responsiblepriestcode;
					}
					else
					{
						this._responsiblepriestcode = default(Nullable<int>);
					}
					this.SendPropertyChanged("responsiblepriest");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="street_family", Storage="_street", ThisKey="streetcode", OtherKey="streetcode", IsForeignKey=true)]
		public street street
		{
			get
			{
				return this._street.Entity;
			}
			set
			{
				street previousValue = this._street.Entity;
				if (((previousValue != value) 
							|| (this._street.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._street.Entity = null;
						previousValue.families.Remove(this);
					}
					this._street.Entity = value;
					if ((value != null))
					{
						value.families.Add(this);
						this._streetcode = value.streetcode;
					}
					else
					{
						this._streetcode = default(Nullable<int>);
					}
					this.SendPropertyChanged("street");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.familydetails")]
	public partial class familydetail
	{
		
		private System.Nullable<int> _familycodedetails;
		
		private string _paxname;
		
		private string _relativity;
		
		private string _birthdate;
		
		private string _birthplace;
		
		private string _mamodia;
		
		private System.Nullable<int> _confesspriestcode;
		
		private string _moahel;
		
		private string _job;
		
		private string _maritalstatus;
		
		private System.Nullable<int> _maritalstatuscode;
		
		private string _socialnumber;
		
		private string _healthstatus;
		
		private string _electionnumber;
		
		private System.Nullable<System.DateTime> _birthdt;
		
		private string _mobile;
		
		private string _email;
		
		private string _paxaddress;
		
		private string _comments;
		
		private System.Nullable<bool> _movedfl;
		
		private System.Nullable<int> _khedmacode;
		
		private System.Nullable<int> _shmosiacode;
		
		private System.Nullable<int> _mamodiacode;
		
		private System.Nullable<int> _housetypecode;
		
		private System.Nullable<int> _churchcode;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		public familydetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familycodedetails", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> familycodedetails
		{
			get
			{
				return this._familycodedetails;
			}
			set
			{
				if ((this._familycodedetails != value))
				{
					this._familycodedetails = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paxname", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string paxname
		{
			get
			{
				return this._paxname;
			}
			set
			{
				if ((this._paxname != value))
				{
					this._paxname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_relativity", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string relativity
		{
			get
			{
				return this._relativity;
			}
			set
			{
				if ((this._relativity != value))
				{
					this._relativity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdate", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string birthdate
		{
			get
			{
				return this._birthdate;
			}
			set
			{
				if ((this._birthdate != value))
				{
					this._birthdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthplace", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string birthplace
		{
			get
			{
				return this._birthplace;
			}
			set
			{
				if ((this._birthplace != value))
				{
					this._birthplace = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamodia", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string mamodia
		{
			get
			{
				return this._mamodia;
			}
			set
			{
				if ((this._mamodia != value))
				{
					this._mamodia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_confesspriestcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> confesspriestcode
		{
			get
			{
				return this._confesspriestcode;
			}
			set
			{
				if ((this._confesspriestcode != value))
				{
					this._confesspriestcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moahel", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string moahel
		{
			get
			{
				return this._moahel;
			}
			set
			{
				if ((this._moahel != value))
				{
					this._moahel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string job
		{
			get
			{
				return this._job;
			}
			set
			{
				if ((this._job != value))
				{
					this._job = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritalstatus", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string maritalstatus
		{
			get
			{
				return this._maritalstatus;
			}
			set
			{
				if ((this._maritalstatus != value))
				{
					this._maritalstatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritalstatuscode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> maritalstatuscode
		{
			get
			{
				return this._maritalstatuscode;
			}
			set
			{
				if ((this._maritalstatuscode != value))
				{
					this._maritalstatuscode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_socialnumber", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string socialnumber
		{
			get
			{
				return this._socialnumber;
			}
			set
			{
				if ((this._socialnumber != value))
				{
					this._socialnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_healthstatus", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string healthstatus
		{
			get
			{
				return this._healthstatus;
			}
			set
			{
				if ((this._healthstatus != value))
				{
					this._healthstatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_electionnumber", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string electionnumber
		{
			get
			{
				return this._electionnumber;
			}
			set
			{
				if ((this._electionnumber != value))
				{
					this._electionnumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthdt", DbType="DateTime2", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> birthdt
		{
			get
			{
				return this._birthdt;
			}
			set
			{
				if ((this._birthdt != value))
				{
					this._birthdt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this._mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paxaddress", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string paxaddress
		{
			get
			{
				return this._paxaddress;
			}
			set
			{
				if ((this._paxaddress != value))
				{
					this._paxaddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this._comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movedfl", DbType="Bit", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<bool> movedfl
		{
			get
			{
				return this._movedfl;
			}
			set
			{
				if ((this._movedfl != value))
				{
					this._movedfl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khedmacode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> khedmacode
		{
			get
			{
				return this._khedmacode;
			}
			set
			{
				if ((this._khedmacode != value))
				{
					this._khedmacode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shmosiacode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> shmosiacode
		{
			get
			{
				return this._shmosiacode;
			}
			set
			{
				if ((this._shmosiacode != value))
				{
					this._shmosiacode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamodiacode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> mamodiacode
		{
			get
			{
				return this._mamodiacode;
			}
			set
			{
				if ((this._mamodiacode != value))
				{
					this._mamodiacode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_housetypecode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> housetypecode
		{
			get
			{
				return this._housetypecode;
			}
			set
			{
				if ((this._housetypecode != value))
				{
					this._housetypecode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> churchcode
		{
			get
			{
				return this._churchcode;
			}
			set
			{
				if ((this._churchcode != value))
				{
					this._churchcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this._SSMA_TimeStamp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.housetypes")]
	public partial class housetype : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _housetypecode;
		
		private string _housetypename;
		
		private EntitySet<family> _families;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnhousetypecodeChanging(int value);
    partial void OnhousetypecodeChanged();
    partial void OnhousetypenameChanging(string value);
    partial void OnhousetypenameChanged();
    #endregion
		
		public housetype()
		{
			this._families = new EntitySet<family>(new Action<family>(this.attach_families), new Action<family>(this.detach_families));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_housetypecode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int housetypecode
		{
			get
			{
				return this._housetypecode;
			}
			set
			{
				if ((this._housetypecode != value))
				{
					this.OnhousetypecodeChanging(value);
					this.SendPropertyChanging();
					this._housetypecode = value;
					this.SendPropertyChanged("housetypecode");
					this.OnhousetypecodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_housetypename", DbType="NVarChar(100)")]
		public string housetypename
		{
			get
			{
				return this._housetypename;
			}
			set
			{
				if ((this._housetypename != value))
				{
					this.OnhousetypenameChanging(value);
					this.SendPropertyChanging();
					this._housetypename = value;
					this.SendPropertyChanged("housetypename");
					this.OnhousetypenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="housetype_family", Storage="_families", ThisKey="housetypecode", OtherKey="housetypecode")]
		public EntitySet<family> families
		{
			get
			{
				return this._families;
			}
			set
			{
				this._families.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.housetype = this;
		}
		
		private void detach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.housetype = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khedma")]
	public partial class khedma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _khedmacode;
		
		private string _khedmaname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkhedmacodeChanging(int value);
    partial void OnkhedmacodeChanged();
    partial void OnkhedmanameChanging(string value);
    partial void OnkhedmanameChanged();
    #endregion
		
		public khedma()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khedmacode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int khedmacode
		{
			get
			{
				return this._khedmacode;
			}
			set
			{
				if ((this._khedmacode != value))
				{
					this.OnkhedmacodeChanging(value);
					this.SendPropertyChanging();
					this._khedmacode = value;
					this.SendPropertyChanged("khedmacode");
					this.OnkhedmacodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khedmaname", DbType="NVarChar(100)")]
		public string khedmaname
		{
			get
			{
				return this._khedmaname;
			}
			set
			{
				if ((this._khedmaname != value))
				{
					this.OnkhedmanameChanging(value);
					this.SendPropertyChanging();
					this._khedmaname = value;
					this.SendPropertyChanged("khedmaname");
					this.OnkhedmanameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mamodia")]
	public partial class mamodia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mamodiacode;
		
		private string _mamodianame;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmamodiacodeChanging(int value);
    partial void OnmamodiacodeChanged();
    partial void OnmamodianameChanging(string value);
    partial void OnmamodianameChanged();
    #endregion
		
		public mamodia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamodiacode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mamodiacode
		{
			get
			{
				return this._mamodiacode;
			}
			set
			{
				if ((this._mamodiacode != value))
				{
					this.OnmamodiacodeChanging(value);
					this.SendPropertyChanging();
					this._mamodiacode = value;
					this.SendPropertyChanged("mamodiacode");
					this.OnmamodiacodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamodianame", DbType="NVarChar(100)")]
		public string mamodianame
		{
			get
			{
				return this._mamodianame;
			}
			set
			{
				if ((this._mamodianame != value))
				{
					this.OnmamodianameChanging(value);
					this.SendPropertyChanging();
					this._mamodianame = value;
					this.SendPropertyChanged("mamodianame");
					this.OnmamodianameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.maritalstatus")]
	public partial class maritalstatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maritalstatuscode;
		
		private string _maritalstatusname;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaritalstatuscodeChanging(int value);
    partial void OnmaritalstatuscodeChanged();
    partial void OnmaritalstatusnameChanging(string value);
    partial void OnmaritalstatusnameChanged();
    #endregion
		
		public maritalstatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritalstatuscode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maritalstatuscode
		{
			get
			{
				return this._maritalstatuscode;
			}
			set
			{
				if ((this._maritalstatuscode != value))
				{
					this.OnmaritalstatuscodeChanging(value);
					this.SendPropertyChanging();
					this._maritalstatuscode = value;
					this.SendPropertyChanged("maritalstatuscode");
					this.OnmaritalstatuscodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maritalstatusname", DbType="NVarChar(100)")]
		public string maritalstatusname
		{
			get
			{
				return this._maritalstatusname;
			}
			set
			{
				if ((this._maritalstatusname != value))
				{
					this.OnmaritalstatusnameChanging(value);
					this.SendPropertyChanging();
					this._maritalstatusname = value;
					this.SendPropertyChanged("maritalstatusname");
					this.OnmaritalstatusnameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.priests")]
	public partial class priest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _priestcode;
		
		private string _priestname;
		
		private string _priestaddress;
		
		private string _priesttel;
		
		private string _priestmobile;
		
		private System.Nullable<int> _churchcode;
		
		private System.Nullable<int> _areacode;
		
		private string _comments;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpriestcodeChanging(int value);
    partial void OnpriestcodeChanged();
    partial void OnpriestnameChanging(string value);
    partial void OnpriestnameChanged();
    partial void OnpriestaddressChanging(string value);
    partial void OnpriestaddressChanged();
    partial void OnpriesttelChanging(string value);
    partial void OnpriesttelChanged();
    partial void OnpriestmobileChanging(string value);
    partial void OnpriestmobileChanged();
    partial void OnchurchcodeChanging(System.Nullable<int> value);
    partial void OnchurchcodeChanged();
    partial void OnareacodeChanging(System.Nullable<int> value);
    partial void OnareacodeChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnSSMA_TimeStampChanging(System.Data.Linq.Binary value);
    partial void OnSSMA_TimeStampChanged();
    #endregion
		
		public priest()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priestcode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int priestcode
		{
			get
			{
				return this._priestcode;
			}
			set
			{
				if ((this._priestcode != value))
				{
					this.OnpriestcodeChanging(value);
					this.SendPropertyChanging();
					this._priestcode = value;
					this.SendPropertyChanged("priestcode");
					this.OnpriestcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priestname", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string priestname
		{
			get
			{
				return this._priestname;
			}
			set
			{
				if ((this._priestname != value))
				{
					this.OnpriestnameChanging(value);
					this.SendPropertyChanging();
					this._priestname = value;
					this.SendPropertyChanged("priestname");
					this.OnpriestnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priestaddress", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string priestaddress
		{
			get
			{
				return this._priestaddress;
			}
			set
			{
				if ((this._priestaddress != value))
				{
					this.OnpriestaddressChanging(value);
					this.SendPropertyChanging();
					this._priestaddress = value;
					this.SendPropertyChanged("priestaddress");
					this.OnpriestaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priesttel", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string priesttel
		{
			get
			{
				return this._priesttel;
			}
			set
			{
				if ((this._priesttel != value))
				{
					this.OnpriesttelChanging(value);
					this.SendPropertyChanging();
					this._priesttel = value;
					this.SendPropertyChanged("priesttel");
					this.OnpriesttelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priestmobile", DbType="NVarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string priestmobile
		{
			get
			{
				return this._priestmobile;
			}
			set
			{
				if ((this._priestmobile != value))
				{
					this.OnpriestmobileChanging(value);
					this.SendPropertyChanging();
					this._priestmobile = value;
					this.SendPropertyChanged("priestmobile");
					this.OnpriestmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> churchcode
		{
			get
			{
				return this._churchcode;
			}
			set
			{
				if ((this._churchcode != value))
				{
					this.OnchurchcodeChanging(value);
					this.SendPropertyChanging();
					this._churchcode = value;
					this.SendPropertyChanged("churchcode");
					this.OnchurchcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areacode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> areacode
		{
			get
			{
				return this._areacode;
			}
			set
			{
				if ((this._areacode != value))
				{
					this.OnareacodeChanging(value);
					this.SendPropertyChanging();
					this._areacode = value;
					this.SendPropertyChanged("areacode");
					this.OnareacodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this.OnSSMA_TimeStampChanging(value);
					this.SendPropertyChanging();
					this._SSMA_TimeStamp = value;
					this.SendPropertyChanged("SSMA_TimeStamp");
					this.OnSSMA_TimeStampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reporttitle")]
	public partial class reporttitle
	{
		
		private string _title;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		public reporttitle()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this._title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this._SSMA_TimeStamp = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.shmosia")]
	public partial class shmosia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _shmosiacode;
		
		private string _shmosianame;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnshmosiacodeChanging(int value);
    partial void OnshmosiacodeChanged();
    partial void OnshmosianameChanging(string value);
    partial void OnshmosianameChanged();
    #endregion
		
		public shmosia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shmosiacode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int shmosiacode
		{
			get
			{
				return this._shmosiacode;
			}
			set
			{
				if ((this._shmosiacode != value))
				{
					this.OnshmosiacodeChanging(value);
					this.SendPropertyChanging();
					this._shmosiacode = value;
					this.SendPropertyChanged("shmosiacode");
					this.OnshmosiacodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shmosianame", DbType="NVarChar(100)")]
		public string shmosianame
		{
			get
			{
				return this._shmosianame;
			}
			set
			{
				if ((this._shmosianame != value))
				{
					this.OnshmosianameChanging(value);
					this.SendPropertyChanging();
					this._shmosianame = value;
					this.SendPropertyChanged("shmosianame");
					this.OnshmosianameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.responsiblepriests")]
	public partial class responsiblepriest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _responsiblepriestcode;
		
		private string _responsiblepriestname;
		
		private string _responsiblepriestaddress;
		
		private string _responsiblepriesttel;
		
		private string _responsiblepriestmobile;
		
		private System.Nullable<int> _churchcode;
		
		private System.Nullable<int> _areacode;
		
		private string _comments;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		private EntitySet<family> _families;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnresponsiblepriestcodeChanging(int value);
    partial void OnresponsiblepriestcodeChanged();
    partial void OnresponsiblepriestnameChanging(string value);
    partial void OnresponsiblepriestnameChanged();
    partial void OnresponsiblepriestaddressChanging(string value);
    partial void OnresponsiblepriestaddressChanged();
    partial void OnresponsiblepriesttelChanging(string value);
    partial void OnresponsiblepriesttelChanged();
    partial void OnresponsiblepriestmobileChanging(string value);
    partial void OnresponsiblepriestmobileChanged();
    partial void OnchurchcodeChanging(System.Nullable<int> value);
    partial void OnchurchcodeChanged();
    partial void OnareacodeChanging(System.Nullable<int> value);
    partial void OnareacodeChanged();
    partial void OncommentsChanging(string value);
    partial void OncommentsChanged();
    partial void OnSSMA_TimeStampChanging(System.Data.Linq.Binary value);
    partial void OnSSMA_TimeStampChanged();
    #endregion
		
		public responsiblepriest()
		{
			this._families = new EntitySet<family>(new Action<family>(this.attach_families), new Action<family>(this.detach_families));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsiblepriestcode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int responsiblepriestcode
		{
			get
			{
				return this._responsiblepriestcode;
			}
			set
			{
				if ((this._responsiblepriestcode != value))
				{
					this.OnresponsiblepriestcodeChanging(value);
					this.SendPropertyChanging();
					this._responsiblepriestcode = value;
					this.SendPropertyChanged("responsiblepriestcode");
					this.OnresponsiblepriestcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsiblepriestname", DbType="NVarChar(50)", UpdateCheck=UpdateCheck.Never)]
		public string responsiblepriestname
		{
			get
			{
				return this._responsiblepriestname;
			}
			set
			{
				if ((this._responsiblepriestname != value))
				{
					this.OnresponsiblepriestnameChanging(value);
					this.SendPropertyChanging();
					this._responsiblepriestname = value;
					this.SendPropertyChanged("responsiblepriestname");
					this.OnresponsiblepriestnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsiblepriestaddress", DbType="NVarChar(100)", UpdateCheck=UpdateCheck.Never)]
		public string responsiblepriestaddress
		{
			get
			{
				return this._responsiblepriestaddress;
			}
			set
			{
				if ((this._responsiblepriestaddress != value))
				{
					this.OnresponsiblepriestaddressChanging(value);
					this.SendPropertyChanging();
					this._responsiblepriestaddress = value;
					this.SendPropertyChanged("responsiblepriestaddress");
					this.OnresponsiblepriestaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsiblepriesttel", DbType="NVarChar(10)", UpdateCheck=UpdateCheck.Never)]
		public string responsiblepriesttel
		{
			get
			{
				return this._responsiblepriesttel;
			}
			set
			{
				if ((this._responsiblepriesttel != value))
				{
					this.OnresponsiblepriesttelChanging(value);
					this.SendPropertyChanging();
					this._responsiblepriesttel = value;
					this.SendPropertyChanged("responsiblepriesttel");
					this.OnresponsiblepriesttelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsiblepriestmobile", DbType="NVarChar(15)", UpdateCheck=UpdateCheck.Never)]
		public string responsiblepriestmobile
		{
			get
			{
				return this._responsiblepriestmobile;
			}
			set
			{
				if ((this._responsiblepriestmobile != value))
				{
					this.OnresponsiblepriestmobileChanging(value);
					this.SendPropertyChanging();
					this._responsiblepriestmobile = value;
					this.SendPropertyChanged("responsiblepriestmobile");
					this.OnresponsiblepriestmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_churchcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> churchcode
		{
			get
			{
				return this._churchcode;
			}
			set
			{
				if ((this._churchcode != value))
				{
					this.OnchurchcodeChanging(value);
					this.SendPropertyChanging();
					this._churchcode = value;
					this.SendPropertyChanged("churchcode");
					this.OnchurchcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areacode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> areacode
		{
			get
			{
				return this._areacode;
			}
			set
			{
				if ((this._areacode != value))
				{
					this.OnareacodeChanging(value);
					this.SendPropertyChanging();
					this._areacode = value;
					this.SendPropertyChanged("areacode");
					this.OnareacodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comments", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				if ((this._comments != value))
				{
					this.OncommentsChanging(value);
					this.SendPropertyChanging();
					this._comments = value;
					this.SendPropertyChanged("comments");
					this.OncommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this.OnSSMA_TimeStampChanging(value);
					this.SendPropertyChanging();
					this._SSMA_TimeStamp = value;
					this.SendPropertyChanged("SSMA_TimeStamp");
					this.OnSSMA_TimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="responsiblepriest_family", Storage="_families", ThisKey="responsiblepriestcode", OtherKey="responsiblepriestcode")]
		public EntitySet<family> families
		{
			get
			{
				return this._families;
			}
			set
			{
				this._families.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.responsiblepriest = this;
		}
		
		private void detach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.responsiblepriest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.streetmap")]
	public partial class streetmap
	{
		
		private System.Nullable<int> _streetcode;
		
		private System.Nullable<int> _areacode;
		
		private System.Nullable<short> _itemorder;
		
		private string _kind;
		
		private string _name;
		
		private string _number;
		
		private System.Nullable<int> _direction;
		
		public streetmap()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_streetcode", DbType="Int")]
		public System.Nullable<int> streetcode
		{
			get
			{
				return this._streetcode;
			}
			set
			{
				if ((this._streetcode != value))
				{
					this._streetcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_areacode", DbType="Int")]
		public System.Nullable<int> areacode
		{
			get
			{
				return this._areacode;
			}
			set
			{
				if ((this._areacode != value))
				{
					this._areacode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_itemorder", DbType="SmallInt")]
		public System.Nullable<short> itemorder
		{
			get
			{
				return this._itemorder;
			}
			set
			{
				if ((this._itemorder != value))
				{
					this._itemorder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kind", DbType="NVarChar(50)")]
		public string kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this._kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="NVarChar(150)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="Int")]
		public System.Nullable<int> direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this._direction = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.streets")]
	public partial class street : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _streetcode;
		
		private string _streetname;
		
		private EntitySet<family> _families;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstreetcodeChanging(int value);
    partial void OnstreetcodeChanged();
    partial void OnstreetnameChanging(string value);
    partial void OnstreetnameChanged();
    #endregion
		
		public street()
		{
			this._families = new EntitySet<family>(new Action<family>(this.attach_families), new Action<family>(this.detach_families));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_streetcode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int streetcode
		{
			get
			{
				return this._streetcode;
			}
			set
			{
				if ((this._streetcode != value))
				{
					this.OnstreetcodeChanging(value);
					this.SendPropertyChanging();
					this._streetcode = value;
					this.SendPropertyChanged("streetcode");
					this.OnstreetcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_streetname", DbType="NVarChar(100)")]
		public string streetname
		{
			get
			{
				return this._streetname;
			}
			set
			{
				if ((this._streetname != value))
				{
					this.OnstreetnameChanging(value);
					this.SendPropertyChanging();
					this._streetname = value;
					this.SendPropertyChanged("streetname");
					this.OnstreetnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="street_family", Storage="_families", ThisKey="streetcode", OtherKey="streetcode")]
		public EntitySet<family> families
		{
			get
			{
				return this._families;
			}
			set
			{
				this._families.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.street = this;
		}
		
		private void detach_families(family entity)
		{
			this.SendPropertyChanging();
			entity.street = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.visitdetails")]
	public partial class visitdetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _familycode;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _details;
		
		private System.Nullable<int> _visitkindcode;
		
		private System.Data.Linq.Binary _SSMA_TimeStamp;
		
		private EntityRef<family> _family;
		
		private EntityRef<visitkind> _visitkind;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfamilycodeChanging(int value);
    partial void OnfamilycodeChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    partial void OnvisitkindcodeChanging(System.Nullable<int> value);
    partial void OnvisitkindcodeChanged();
    partial void OnSSMA_TimeStampChanging(System.Data.Linq.Binary value);
    partial void OnSSMA_TimeStampChanged();
    #endregion
		
		public visitdetail()
		{
			this._family = default(EntityRef<family>);
			this._visitkind = default(EntityRef<visitkind>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_familycode", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int familycode
		{
			get
			{
				return this._familycode;
			}
			set
			{
				if ((this._familycode != value))
				{
					if (this._family.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfamilycodeChanging(value);
					this.SendPropertyChanging();
					this._familycode = value;
					this.SendPropertyChanged("familycode");
					this.OnfamilycodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime2", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string details
		{
			get
			{
				return this._details;
			}
			set
			{
				if ((this._details != value))
				{
					this.OndetailsChanging(value);
					this.SendPropertyChanging();
					this._details = value;
					this.SendPropertyChanged("details");
					this.OndetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitkindcode", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> visitkindcode
		{
			get
			{
				return this._visitkindcode;
			}
			set
			{
				if ((this._visitkindcode != value))
				{
					if (this._visitkind.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnvisitkindcodeChanging(value);
					this.SendPropertyChanging();
					this._visitkindcode = value;
					this.SendPropertyChanged("visitkindcode");
					this.OnvisitkindcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSMA_TimeStamp", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary SSMA_TimeStamp
		{
			get
			{
				return this._SSMA_TimeStamp;
			}
			set
			{
				if ((this._SSMA_TimeStamp != value))
				{
					this.OnSSMA_TimeStampChanging(value);
					this.SendPropertyChanging();
					this._SSMA_TimeStamp = value;
					this.SendPropertyChanged("SSMA_TimeStamp");
					this.OnSSMA_TimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="family_visitdetail", Storage="_family", ThisKey="familycode", OtherKey="familycode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public family family
		{
			get
			{
				return this._family.Entity;
			}
			set
			{
				family previousValue = this._family.Entity;
				if (((previousValue != value) 
							|| (this._family.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._family.Entity = null;
						previousValue.visitdetail = null;
					}
					this._family.Entity = value;
					if ((value != null))
					{
						value.visitdetail = this;
						this._familycode = value.familycode;
					}
					else
					{
						this._familycode = default(int);
					}
					this.SendPropertyChanged("family");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="visitkind_visitdetail", Storage="_visitkind", ThisKey="visitkindcode", OtherKey="visitkindcode", IsForeignKey=true, DeleteRule="CASCADE")]
		public visitkind visitkind
		{
			get
			{
				return this._visitkind.Entity;
			}
			set
			{
				visitkind previousValue = this._visitkind.Entity;
				if (((previousValue != value) 
							|| (this._visitkind.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._visitkind.Entity = null;
						previousValue.visitdetails.Remove(this);
					}
					this._visitkind.Entity = value;
					if ((value != null))
					{
						value.visitdetails.Add(this);
						this._visitkindcode = value.visitkindcode;
					}
					else
					{
						this._visitkindcode = default(Nullable<int>);
					}
					this.SendPropertyChanged("visitkind");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.visitkinds")]
	public partial class visitkind : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _visitkindcode;
		
		private string _visitkindname;
		
		private EntitySet<visitdetail> _visitdetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvisitkindcodeChanging(int value);
    partial void OnvisitkindcodeChanged();
    partial void OnvisitkindnameChanging(string value);
    partial void OnvisitkindnameChanged();
    #endregion
		
		public visitkind()
		{
			this._visitdetails = new EntitySet<visitdetail>(new Action<visitdetail>(this.attach_visitdetails), new Action<visitdetail>(this.detach_visitdetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitkindcode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int visitkindcode
		{
			get
			{
				return this._visitkindcode;
			}
			set
			{
				if ((this._visitkindcode != value))
				{
					this.OnvisitkindcodeChanging(value);
					this.SendPropertyChanging();
					this._visitkindcode = value;
					this.SendPropertyChanged("visitkindcode");
					this.OnvisitkindcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitkindname", DbType="NVarChar(100)")]
		public string visitkindname
		{
			get
			{
				return this._visitkindname;
			}
			set
			{
				if ((this._visitkindname != value))
				{
					this.OnvisitkindnameChanging(value);
					this.SendPropertyChanging();
					this._visitkindname = value;
					this.SendPropertyChanged("visitkindname");
					this.OnvisitkindnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="visitkind_visitdetail", Storage="_visitdetails", ThisKey="visitkindcode", OtherKey="visitkindcode")]
		public EntitySet<visitdetail> visitdetails
		{
			get
			{
				return this._visitdetails;
			}
			set
			{
				this._visitdetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_visitdetails(visitdetail entity)
		{
			this.SendPropertyChanging();
			entity.visitkind = this;
		}
		
		private void detach_visitdetails(visitdetail entity)
		{
			this.SendPropertyChanging();
			entity.visitkind = null;
		}
	}
}
#pragma warning restore 1591
